### PR TITLE
fix(share-tweet-copy): fix button style on status page

### PR DESCRIPTION
**Pull request by Nicklaus6**

### CODE REVIEW

**Review by screw-hand — APPROVED** [review]
The `executed` is declared in `handleTempStyleStatusPage` **instead of in the returned function definition** because: a singleton pattern is used here, and only the top (i.e., the first) tweet style of the `/status/` page needs special handling.

You should restore the code here.

**Comment by screw-hand** [comment]
1. Closure creates memory that cannot be reclaimed. This is indeed a closed flaw.
2. Using closures keeps the singleton pattern since you only need to style the first tweet on the `/status/` page.
3. If the singleton pattern is not required, there is no need to use closures.

**Review by screw-hand — APPROVED** [review]

**Comment by Nicklaus6** [comment]
> 1. Closure creates memory that cannot be reclaimed. This is indeed a closed flaw.
> 2. Using closures keeps the singleton pattern since you only need to style the first tweet on the `/status/` page.
> 3. If the singleton pattern is not required, there is no need to use closures.

So I think it's unnecessary to use IFFE .

**Comment by screw-hand** [comment]
v0.3.14 released.

**Pull request merged**
